# -*- coding: utf-8 -*-
# Auto-generated by CADBoard for 引桥桥墩
# component_id: 77e926f0-8423-43f6-a402-e371906b1929
# generated_at: 2026-06-29 23:10:56
# placement: (0.0, 200.0, 0.0)

from pyp3d import *
import math
import sys

# create_geometry/place_to 依赖 sys.argv[0] 读取 DependentFile
if hasattr(sys, '_original_argv0'):
    sys.argv[0] = sys._original_argv0
else:
    sys.argv[0] = 'C:\\ProgramData\\PKPM\\BIMBase\\Plugins\\Pro\\V1.6\\pythonplugin\\CADBoard\\utils\\generated_component_cache.py'

class 引桥桥墩_77e926f0_8423_43f6_a402_e371906b(Component):
    """引桥桥墩：带斜边和凸起的盖梁 + 双墩柱 + 多根系梁"""

    def __init__(self):
        Component.__init__(self)
        self['盖梁总长'] = Attr(1930.000000, obvious=True)
        self['盖梁总高'] = Attr(300.000000, obvious=True)
        self['盖梁宽'] = Attr(300.000000, obvious=True)
        self['墩柱直径'] = Attr(250.000000, obvious=True)
        self['墩柱间距'] = Attr(1140.000000, obvious=True)
        self['墩高'] = Attr(1200.000000, obvious=True)
        self['系梁根数'] = Attr(2, obvious=True)
        self['引桥桥墩'] = Attr(None, show=True)
        self.replace()

    @export
    def replace(self):
        cap_l = self['盖梁总长']
        cap_h = self['盖梁总高']
        cap_w = self['盖梁宽']
        col_d = self['墩柱直径']
        col_s = self['墩柱间距']
        col_h = self['墩高']
        tie_n = int(self['系梁根数'])

        # 细部尺寸固定为图纸默认值
        boss_w = 30.0
        boss_h = 50.0
        cap_bottom_w = 1390.0
        chamfer_h = 120.0
        tie_w = 200.0
        tie_h = 200.0
        tie_start = 200.0
        tie_step = 500.0
        # 系梁长随墩柱间距自动适配
        tie_l = max(col_s - col_d, 100.0)

        half_l = cap_l / 2.0
        half_bottom = cap_bottom_w / 2.0
        mid_h = cap_h - boss_h

        # 盖梁整体截面（含梯形台、矩形主体、顶部两端凸起），一次 Sweep 成型
        outer = Section(
            Vec2(-half_bottom, 0),
            Vec2(half_bottom, 0),
            Vec2(half_l, chamfer_h),
            Vec2(half_l, cap_h),
            Vec2(-half_l, cap_h),
            Vec2(-half_l, chamfer_h)
        )
        inner = Section(
            Vec2(-half_l + boss_w, mid_h),
            Vec2(half_l - boss_w, mid_h),
            Vec2(half_l - boss_w, cap_h),
            Vec2(-half_l + boss_w, cap_h)
        )
        section = rotate(Vec3(1, 0, 0), 0.5 * math.pi) * (outer - inner)
        path = Line(Vec3(0, -cap_w / 2, 0), Vec3(0, cap_w / 2, 0))
        cap = translate(0, 0, col_h) * Sweep(section, path)

        # 墩柱（2根，圆柱）
        col_r = col_d / 2.0
        col1 = translate(-col_s / 2, 0, col_h / 2) * Cone(Vec3(0, 0, -col_h / 2), Vec3(0, 0, col_h / 2), col_r, col_r)
        col2 = translate(col_s / 2, 0, col_h / 2) * Cone(Vec3(0, 0, -col_h / 2), Vec3(0, 0, col_h / 2), col_r, col_r)

        # 系梁
        ties = None
        if tie_n > 0 and col_h > 0:
            for i in range(tie_n):
                z_top = col_h - tie_start - i * tie_step
                z = z_top - tie_h / 2
                if z < 0:
                    z = 0
                tie = translate(0, 0, z + tie_h / 2) * Cone(Vec3(-tie_l / 2, 0, 0), Vec3(tie_l / 2, 0, 0), tie_h / 2, tie_h / 2)
                if ties is None:
                    ties = tie
                else:
                    ties = Combine(ties, tie)

        parts = [cap, col1, col2]
        if ties is not None:
            parts.append(ties)
        self['引桥桥墩'] = Combine(*parts)


if __name__ == "__main__":
    comp = 引桥桥墩_77e926f0_8423_43f6_a402_e371906b()
    pos = translate(0.000000, 200.000000, 0.000000)

    # 方案1：create_geometry 自动放置，并校验返回的 entityId 是否真正有效
    auto_ok = False
    try:
        eid = create_geometry(pos * comp)
        try:
            from pyp3d import entityid_isvaid
            auto_ok = entityid_isvaid(eid)
        except Exception:
            auto_ok = True  # 无法校验时默认成功
        if auto_ok:
            print("[OK] create_geometry placed with valid entityId")
        else:
            print("[WARN] create_geometry returned invalid entityId, will fallback")
    except Exception as e:
        print(f"[WARN] create_geometry failed: {e}, will fallback")

    # 方案2：启动 BIMBase 手动放置工具（与 组件测试/引桥桥墩.py 一致）
    if not auto_ok:
        try:
            place(comp)
            print("[OK] place() manual placement tool started")
        except Exception as e2:
            print(f"[ERROR] place() also failed: {e2}")
